// Typed access to the build-time content manifest. The JSON is generated by
// plugins/vite-plugin-content.ts on dev-server start and on each build.
import raw from "../generated/manifest.json";
import type { GroupMeta, Manifest, NoteMeta } from "./types";

export const manifest = raw as Manifest;

const noteBySlug = new Map(manifest.notes.map((n) => [n.slug, n]));
const groupBySlug = new Map(manifest.groups.map((g) => [g.slug, g]));

export function getNote(slug: string): NoteMeta | undefined {
  return noteBySlug.get(slug);
}

export function getGroup(slug: string): GroupMeta | undefined {
  return groupBySlug.get(slug);
}

export function allNotes(): NoteMeta[] {
  return manifest.notes;
}

function byRecency(a: NoteMeta, b: NoteMeta): number {
  if (a.date && b.date) return a.date < b.date ? 1 : -1;
  if (a.date) return -1;
  if (b.date) return 1;
  return a.title.localeCompare(b.title);
}

// Notes ordered newest-first for index listings.
export function recentNotes(): NoteMeta[] {
  return [...manifest.notes].sort(byRecency);
}

// Starred/featured notes for the curated section, newest-first.
export function starredNotes(): NoteMeta[] {
  return manifest.notes.filter((n) => n.star).sort(byRecency);
}

// Notes belonging to a folder-group (by group path, e.g. "projects").
export function notesInGroup(groupPath: string): NoteMeta[] {
  return manifest.notes.filter((n) => n.group === groupPath).sort(byRecency);
}

// Display group for a note in listings (e.g. "systems/"). Root notes → "".
export function groupLabel(note: NoteMeta): string {
  return note.group === "root" ? "" : `${note.group}/`;
}

// First PDF among a note's artifact links, if any.
export function pdfArtifact(note: NoteMeta): string | undefined {
  return note.artifacts.find((a) => a.href.toLowerCase().endsWith(".pdf"))?.href;
}

// A page with no body text but a PDF link is really just a pointer to that PDF —
// visiting it should open the PDF directly instead of an empty note.
export function isPdfOnly(note: NoteMeta): boolean {
  return note.wordCount === 0 && !!pdfArtifact(note);
}
